name: PayToKeep
version: '${project.version}'
main: lol.niox.paytokeep.PayToKeep
api-version: '1.20'
commands:
  buykp:
    description: 购买保留物品
    usage: /<command>
  setkpprice:
    description: 设置保留物品价格
    usage: /<command> <price>
  switchkp:
    description: 开关保留物品
    usage: /<command>
  salvage:
    description: 恢复物品
    usage: /<command>
  setsalvageprice:
    description: 设置恢复物品价格
    usage: /<command> <price>
  setexpire:
    description: 设置恢复物品过期时间
    usage: /<command> <time>
  kpstatus:
    description: 查看保留物品状态
    usage: /<command>