name: PayToKeep
version: '${project.version}'
main: lol.niox.paytokeep.PayToKeep
api-version: '1.20'
commands:
  kpbuy:
    description: 购买保留物品
    usage: /<command>
  kpsetprice:
    description: 设置保留物品价格
    usage: /<command> <price>
  kpswitch:
    description: 开关保留物品
    usage: /<command>
  kpstatus:
    description: 查看保留物品状态
    usage: /<command>
  salvage:
    description: 恢复物品
    usage: /<command>
  salvagesetprice:
    description: 设置恢复物品价格
    usage: /<command> <price>
  salvagesetexpire:
    description: 设置恢复物品过期时间
    usage: /<command> <time>
