name: PayToKeep
version: '${project.version}'
main: lol.niox.paytokeep.PayToKeep
api-version: '1.20'
commands:
  buyinv:
    description: 购买保留物品
    usage: /<command>
  setinvprice:
    description: 设置保留物品价格
    usage: /<command> <price>